development:
  :address: oxmail.registrar-servers.com
  :port: 25
  :authentication: plain
  :user_name: hello@famiytales.co
  :password: IVEYmba2013
  :enable_starttls_auto: true
production:
  :address: oxmail.registrar-servers.com
  :port: 25
  :authentication: plain
  :user_name: hello@famiytales.co
  :password: IVEYmba2013
  :enable_starttls_auto: true