development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :domain: familytales.co
  :user_name: hello@famiytales.co
  :password: IVEYmba2013
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :domain: familytales.co
  :user_name: hello@famiytales.co
  :password: IVEYmba2013
  :enable_starttls_auto: true