development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: FamilyTalesInc@gmail.com
  :password: IVEYmba2013
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: FamilyTalesInc@gmail.com
  :password: IVEYmba2013
  :enable_starttls_auto: true