development:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: plain
  :user_name: hello@thefamilytales.com
  :password: xPkondLc5P85dSOpmLpuPQ
  :enable_starttls_auto: true
production:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: plain
  :user_name: hello@thefamilytales.com
  :password: xPkondLc5P85dSOpmLpuPQ
  :enable_starttls_auto: true