development:
  bucket: familytales-dev
  access_key_id: AKIAJ3AJTP2LJGWA6YPQ
  secret_access_key: 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
test:
  bucket: familytales-test
  access_key_id: AKIAJ3AJTP2LJGWA6YPQ
  secret_access_key: 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
production:
  bucket: familytales-prod
  access_key_id: AKIAJ3AJTP2LJGWA6YPQ
  secret_access_key: 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